language: java
jdk:
  - oraclejdk8
  
services:
  - mongodb

before_script:
  - sleep 15
  - mongo board --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

install:
    - mvn -N io.takari:maven:wrapper
    - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
    - mvn -N io.takari:maven:wrapper
    - ./mvnw clean test jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN